spring:
  config:
    activate:
      on-profile: docker
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db-server:5432/test_database
    username: root
    password: root

logging:
  level:
    bg:
      vivacom:
        combine:
          save:
            debundler: "info"
  file:
    path: ${user.home}/LOGS/SportBettingOdds/

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test_database
    username: root
    password: root
server:
  port: 8023
logging:
  level:
    bg:
      vivacom:
        combine:
          save:
            debundler: "info"
  file:
    path: ${user.home}/LOGS/SportBettingOdds/
